#
# Yocto run support for devel containers.
#

if [ "$HOST_DEVICE_KVM" ]; then
	DEVICE_KVM="${HOST_DEVICE_KVM}"

	DOCKER_RUN_ARGS_ENV="$(run_docker_args_add "$DOCKER_RUN_ARGS_ENV" "--cap-add=SYS_ADMIN" $HOST_CONTAINER_NOT_PRIVILEGED)"
	DOCKER_RUN_ARGS_ENV="$(run_docker_args_add "$DOCKER_RUN_ARGS_ENV" "--cap-add=SYS_RAWIO" $HOST_CONTAINER_NOT_PRIVILEGED)"
	DOCKER_RUN_ARGS_MAP="$(run_docker_args_add "$DOCKER_RUN_ARGS_MAP" "--device $HOST_DEVICE_KVM:$DEVICE_KVM" $HOST_CONTAINER_NOT_PRIVILEGED)"
fi

if [ "$HOST_DEVICE_LOOP" ]; then
	DEVICE_LOOP="${HOST_DEVICE_LOOP}"

	DOCKER_RUN_ARGS_ENV="$(run_docker_args_add "$DOCKER_RUN_ARGS_ENV" "--cap-add=SYS_ADMIN" $HOST_CONTAINER_NOT_PRIVILEGED)"
	DOCKER_RUN_ARGS_ENV="$(run_docker_args_add "$DOCKER_RUN_ARGS_ENV" "--cap-add=SYS_RAWIO" $HOST_CONTAINER_NOT_PRIVILEGED)"
	DOCKER_RUN_ARGS_MAP="$(run_docker_args_add "$DOCKER_RUN_ARGS_MAP" "--device $HOST_DEVICE_LOOP:$DEVICE_LOOP" $HOST_CONTAINER_NOT_PRIVILEGED)"
fi
